name: Check Custom Actions Syntax

on:
  push:
    paths:
      - '.github/actions/**/*.yml'
  pull_request:
    paths:
      - '.github/actions/**/*.yml'

jobs:
  lint:
    name: Validate GitHub Actions Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install actionlint
        run: |
          curl -sSLf https://github.com/rhysd/actionlint/releases/download/v1.6.4/actionlint_1.6.4_linux_amd64.tar.gz | tar xzv
          chmod +x actionlint

      - name: Check GitHub Actions Syntax in Custom Actions
        run: |
          for file in $(find .github/actions -name "*.yml"); do
            ./actionlint "$file"
          done
