name: Check Syntax

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

env:
  ACTIONLINT_VERSION: 1.6.25
  INSTALL_PATH: /usr/local/bin

jobs:
  lint:
    name: Validate Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine latest yamllint version
        id: get-yamllint-version
        run: |
          LATEST_VERSION=$(curl -s https://pypi.org/pypi/yamllint/json | jq -r .info.version)
          echo "YAMLLINT_VERSION=${LATEST_VERSION}" >> "${GITHUB_ENV}"

      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: ${{ env.INSTALL_PATH }}
          key: tools-${{ env.ACTIONLINT_VERSION }}-${{ env.YAMLLINT_VERSION }}

      - name: Install actionlint
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl -sSLf https://github.com/rhysd/actionlint/releases/download/v${{ env.ACTIONLINT_VERSION }}/actionlint_${{ env.ACTIONLINT_VERSION }}_linux_amd64.tar.gz | tar xzv -C ${{ env.INSTALL_PATH }}

      - name: Install yamllint
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          pip install --target=${{ env.INSTALL_PATH }} yamllint==${{ env.YAMLLINT_VERSION }}

      - name: Check YAML Syntax for All Files
        run: |
          find . -name "*.yml" -o -name "*.yaml" | while read -r file; do
            yamllint "$file"
          done

      - name: Check GitHub Actions Workflow Syntax
        run: |
          find .github/workflows -name "*.yml" -o -name "*.yaml" | while read -r file; do
            actionlint "$file"
          done
